version: '3.6'
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: sharesense_development
      POSTGRES_USER: '${USER}'
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:

