# Generated by Django 3.2.12 on 2022-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesenseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senseuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='senseuser',
            name='name',
        ),
        migrations.AddField(
            model_name='senseuser',
            name='cam_ip',
            field=models.CharField(default='localhost', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senseuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'regular_user'), (1, 'good_people'), (2, 'dispatch')], default=0),
        ),
    ]
